### ISSUE TITLE
[Bug] File Upload limitations

### ISSUE THREAD

**Issue by davkra** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-backend#97]
# Describe the bug
File Uploads of highlights, pictures, videos or other media does not work in case the file in the form is too large.

## Potential Solution

Set the size in the `application.yml`:
```
quarkus:
  http:
    limits:
      max-form-attribute-size: 4M
```
